@startuml bot
title conversation flow
scale 2

actor person order 10
actor employee order 40
participant bot order 20
participant "citynet api" as ca order 30

person -> bot : CITYBOT
bot -> person : Hallo...
bot -> person : privacy info
bot -> person : proberen?
alt ja
    bot -> person : wil je een voorbeeldvraag?
    alt ja
        bot -> person : Waar kan ik mijn woonwagen parkeren? 
        person -> bot : [button] ok bedankt
        bot -> person : stel gerust je vraag
    else nee
        bot -> person : Ga je gang
    end
    bot -> person : stel je vraag
    person -> bot : vraag
    bot -> ca ++: dispatch question
    ca -> bot --: documents
    bot -> person: zijn dit de juiste concepten?
    alt ja
        bot -> person : documents
        bot -> person: indien je nog een vraag hebt, stuur CITYBOT
    else nee 
        bot -> person : stel je vraag opnieuw
    end
else neen
    bot -> person : geen probleem
else medewerker
    bot -> person : een mederwerker komt hierop terug
end
@enduml